[build]
    command = "npx @11ty/eleventy"
    publish = "_site"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"
        Permissions-Policy = "interest-cohort=()"

[[headers]]
    for = "/sample-files/*"
    [headers.values]
        X-Frame-Options = "SAMEORIGIN"
